# Specify Base image
From alpine

# Download and install dependency(ies).
Run apk add --update redis
Run apk add --update gcc


# Tell the image what to do when it starts as a container
CMD ["redis-server"]
